runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /(.*\.(gif|png|jpg|css|js)(|\.map))$
  static_files: dist/vtai-todo-app-frontend/\1
  upload: dist/vtai-todo-app-frontend/(.*)(|\.map)

- url: /(.*)
  static_files: dist/vtai-todo-app-frontend/index.html
  upload: dist/vtai-todo-app-frontend/index.html
  

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE