
steps:

  # Install node packages
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'install', '--save', '--legacy-peer-deps']

    # Create Environment file
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'run', 'create-env' ]
    env:
    - 'API_KEY=${_API_KEY}'

  # Install Dev Dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'install', '-g', 'typescript' ]

  # Build productive files
  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'run', 'build', '--prod' ]

  - name: 'bash'
    args: [cp,'.env','build']

  # Deploy to google cloud app egnine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--version=prod']